### ISSUE TITLE
Use plugin version rather than file time

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-content-converter#13]
Some file systems are distributed, which means that the file modified time can differ between web requests. As such, using `filemtime()` to determine when a file was last modified can be unreliable and cause problems.

As `filemtime()` is most commonly used for cache-busting purposes after plugin updates a better method is to have the plugin set a version number in code (e.g. through a constant) that can be used throughout the plugin as a cache buster string.

**Comment by iuravic** [comment]
Implemented in newer versions of the plugin.
