### ISSUE TITLE
Don't convert content that's already using blocks

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-content-converter#20]
**Describe the conversion bug**
Converting a post that is already using blocks converts the post into a bunch of `raw HTML` blocks. 

**Expected behavior**
It would be best if posts containing blocks were skipped by the content converter. There should be a standard way available in the WP source code that the block editor uses to determine whether to put all the post content inside a classic block. We should use that check to determine whether a post can be converted or not.

**Comment by iuravic** [comment]
Already resolved in newer versions of the plugin.
