### ISSUE TITLE
Can using this plugin fix Gallery created using Classic Editor?

### ISSUE THREAD

**Issue by akkiverma** [Automattic/newspack-content-converter#25]
Can converting posts using this plugin fix the galleries created using the classic editor?

At present, if a post has a gallery created using the classic editor in past, it is only showing the first image of the gallery. Here's an example - https://www.reviewcenter.in/8009/vivo-v11-pro-review-the-best-in-the-game/

There are so many posts with galleries, hence I need to know if converting the posts using this plugin or any other plugin available in WordPress repository fix this issue?

or for Newspack, we have to use this plugin only?

**Comment by iuravic** [comment]
Closing this issue due to old age. If the topic is still in need for solution, let's open a fresh issue.
