### ISSUE TITLE
Remove unnecessary UI elements

### ISSUE THREAD

**Issue by iuravic** [Automattic/newspack-content-converter#42]
As noticed here, there's no need for the following UI elements on the Settings page:
Conversion params -- Conversion batch size -- this is an internal param, definitely better not to let the user change this
Queued stats -- number of entries to be converted -- this is displayed on the "Run Conversion" page, no need for double here.
Remove those completely.

**Comment by thomasguillot** [comment]
See 5c6adb4

**Comment by thomasguillot** [comment]
Fixed via #41
