### ISSUE TITLE
WordPress CSS conflict produces blue screen, no progress

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-content-converter#88]
The latest version of WordPress changed some CSS in Gutenberg, so the Content Converter UI is now broken — we get a blue screen instead.

However for now until we fix the Converter, we can still use and run the Converter this way:

* run Converter as usual, instead of the UI showing progress, when the conversion starts and you see a blue screen in Editor area, open the Console, and monitor the progress
* everything will work as usual, except the UI is not visible until we fix it

**Comment by thomasguillot** [comment]
Fixed https://github.com/Automattic/newspack-content-converter/pull/65
